print("Введите два числа")
a = int(input())
b = int(input())
print("Сумма", a+b)
print("Разность", a-b)
print("Среднее арифметическое", (a+b)/2)
print("Произведение", a*b)
print("Частное", a/b)
